server:
  port: 8081
spring:
  application:
   name: USER-SERVICE

  datasource:
    url: jdbc:mysql://localhost:3306/shop?useSSL=false&serverTimezone=UT&&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

# Hibernate Configuration (Optional, but recommended)
  jpa:
   hibernate:
    ddl-auto: update
   properties:
      hibernate.transaction.jta.platform: org.hibernate.engine.transaction.internal.jta.JtaPlatformHelper$None  # Explicitly disable JTA

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-59956631.okta.com/oauth2/default

      client:
        registration:
          my-internal-client:
            provider: okta
            authorization-grant-type: client_credentials
            scope: internal
            client-id: 0oaorud41niG55DOT5d7
            client-secret: 6GMelqmsGa7epB20simSCTqo65xU-ATzx2YjXHvEYvAm1-4H4XyfPTipiRx1hy3E


        provider:
          okta:
            issuer-uri: https://dev-59956631.okta.com/oauth2/default







eureka:
  instance:
    prefer-ip-address: true

  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"

  health:
    show-details: always
    diskspace:
        enabled: true


okta:
  oauth2:
    issuer: https://dev-59956631.okta.com/oauth2/default
    audience: api://default

logging:
  level:
    org.springframework.security: DEBUG
    feign: DEBUG