server:
  port: 8086

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**
        - id: item-service
          uri : lb://ITEM-SERVICE
          predicates:
            - Path=/item/**

#Okta Configuration
okta:
  oauth2:
    issuer: https://dev-59956631.okta.com/oauth2/default
    audience: api://default
    client-id: 0oaorud41niG55DOT5d7
    client-secret: 6GMelqmsGa7epB20simSCTqo65xU-ATzx2YjXHvEYvAm1-4H4XyfPTipiRx1hy3E
    scopes: openid, profile, email, offline_access

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


logging:
  level:
    org.springframework.security: DEBUG
    feign: DEBUG